# Generated by Django 4.2.3 on 2023-07-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveSmallIntegerField(blank=True, default=0)),
                ("is_auto_generated", models.BooleanField(default=False)),
            ],
        ),
    ]
