# Generated by Django 4.2.3 on 2023-07-28 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0006_animal_created_at_animal_modified_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={"ordering": ["modified_at", "name"]},
        ),
    ]
