# Generated by Django 4.2.3 on 2023-08-08 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0007_alter_animal_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={"ordering": ["-modified_at", "name"]},
        ),
    ]
