# Generated by Django 4.2.3 on 2023-08-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0008_alter_animal_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="state",
            field=models.CharField(choices=[("good", "Good"), ("bad", "Bad")], default="good", max_length=100),
        ),
    ]
