# Generated by Django 4.2.3 on 2023-08-08 17:35
import random
from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from apps.animals import models as animals_models


def create_and_set_animal_kind(
    apps,
    schema_editor,  # noqa: F841
):
    Animal: "animals_models.Animal" = apps.get_model("animals", "Animal")
    Kind: "animals_models.Kind" = apps.get_model("animals", "Kind")

    animals_for_update__queryset = Animal.objects.filter(kind__isnull=True).all()

    if not animals_for_update__queryset.exists():
        return

    kinds = []

    for kind_as_str in ("Dog", "Cat"):
        kind, is_created = Kind.objects.get_or_create(name=kind_as_str)
        kinds.append(kind)

    for animal in animals_for_update__queryset:
        selected_kind = random.choice(kinds)

        animal.kind = selected_kind
        animal.save()

    # animals_for_update__queryset.update(kind=kind)


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0010_kind_animal_kind"),
    ]

    operations = [
        migrations.RunPython(
            code=create_and_set_animal_kind,
            reverse_code=migrations.RunPython.noop,
        )
    ]
