# Generated by Django 4.2.3 on 2023-08-08 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0011_create_and_set_animal_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="animals", to="animals.kind"
            ),
        ),
        migrations.AlterField(
            model_name="kind",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
