# Generated by Django 4.2.3 on 2023-08-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0012_alter_animal_kind_alter_kind_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="animal",
            name="colors",
            field=models.ManyToManyField(related_name="animals", to="animals.color"),
        ),
    ]
